# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a356baf5961e3035721530e2f982ed2fc83bdb0b63a0241777512059cd920a94fccef32f8ea09b9aab098bcd33bdc7940120be09ea41f55da4f054d43b3b8f1f

test:
  secret_key_base: 123a50887886c5c4c58a94e14c091d86da73636224497d0ab4bbc94f9eea76df1d38a84c870d61fce495fb777609ad26bb286a70cb2f3c235b6cc8947b22d88e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
